network:
    name: {ergo_network}

server:
    name: {hostname}
    listeners:
        ":6667": {}
        ":6697":
            tls:
                key: /opt/ergo/certs/server.key
                cert: /opt/ergo/certs/server.crt
    motd: ergo.motd
    
    motd-formatting: true
    relaymsg:
        enabled: false
    max-sendq: 96k
    ip-limits:
        count: false
        throttle: false
    ip-cloaking:
        enabled: false
    secure-nets: []
    forwards: []
    check-ident: false
    lookup-hostnames: false
    forward-confirm-hostnames: false
    output-path: ircd.log
    log-level: info
    modes: +nt
    relaymsg-separators: "/"
    max-line-len: 512

logging:
    - method: stderr
      type: "* -userinput -useroutput"
      level: info

debug:
    recover-from-errors: true
    profiling: false
    stack-impacting: false

datastore:
    path: ircd.db

accounts:
    authentication-enabled: true
    registration:
        enabled: true
        allow-before-connect: true
        throttling:
            enabled: true
            duration: 10m
            max-attempts: 30
        bcrypt-cost: 9
        verify-timeout: 120h
        enabled-callbacks:
            - none
    require-sasl:
        enabled: false
        exempted:
            - "localhost"
            - "127.0.0.1"
    nick-reservation:
        enabled: true
        additional-nick-limit: 2
        method: strict
        allow-custom-enforcement: false
        guest-nickname-format: "Guest-*"
        force-guest-format: false
        force-nick-equals-account: false
    multiclient:
        enabled: true
        allowed-by-default: true
        always-on: "opt-out"
        auto-away: "opt-out"
        always-on-expiration: 90d

channels:
    default-modes: +nt
    max-channels-per-client: 100
    registration:
        enabled: true
        max-channels-per-account: 15

limits:
    nicklen: 32
    identlen: 20
    channellen: 64
    awaylen: 390
    kicklen: 390
    topiclen: 390
    monitor-entries: 100
    whowas-entries: 100
    registration-messages: 1024

history:
    enabled: true
    channel-length: 2048
    client-length: 256
    autoreplay-on-join: 0
    autoresize-window: 3d
    persistent:
        enabled: false
        unregistered-channels: false
        registered-channels: "opt-out"
        direct-messages: "opt-out"
    retention:
        allow-individual-delete: false
        enable-account-indexing: false
    tagmsg-storage:
        default: false
        whitelist:
            - "+draft/react"
            - "+draft/reply"

filename-format:
    timestamp: "2006-01-02T15:04:05.000Z07:00"
    search: "search"

sno-masks:
    enabled: true
    default: "a"
    user-masks: false